### ISSUE TITLE
"Event loop is too fast"

### ISSUE THREAD

**Issue by davidhyman** [bharel/asynciolimiter#14]
Using the `asynciolimiter.Limiter` I'm hitting this assertion, unsure what's to be done about it;

```
site-packages\asynciolimiter\__init__.py", line 356, in _wakeup
    assert -leftover_time < self._time_between_calls, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Event loop is too fast. Woke up 1.9999999979821346 ticks early.
```

On Python 3.12, rate limit of ~166.666 with 156 tasks

**Comment by bharel** [comment]
Oh that's intriguing. It somehow means that the event loop time.sleep is shorter than the actual time slept.

I think to think of the implications. Maybe it's due to clock or float precision.

**Comment by bharel** [comment]
Uhhhh... Technically it's a bug in Python or the operating system I believe...

That assertion is not too harmful but does indicate a highly inaccurate system clock or a different event loop issue that will increase CPU utilization.  It won't run on `py -o` which you would usually use in production.

I might remove it and change to a `warnings.warning` (`ResourceWarning`).

Would you mind removing that assertion locally and switching to `logging.warning`?
Tell me how often does that warning actually pops up, and the operating system.

**Comment by bharel** [comment]
Are you using Windows x64 by any chance? Seems like there's an issue at python/cpython#110695 with monotonic clock accuracy causing `call_at` to be scheduled earlier than two clock ticks.

**Comment by River-Shi** [comment]
> Using the `asynciolimiter.Limiter` I'm hitting this assertion, unsure what's to be done about it;
> 
> ```
> site-packages\asynciolimiter\__init__.py", line 356, in _wakeup
>     assert -leftover_time < self._time_between_calls, (
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AssertionError: Event loop is too fast. Woke up 1.9999999979821346 ticks early.
> ```
> 
> On Python 3.12, rate limit of ~166.666 with 156 tasks

same error:
```
Exception in callback <bound method Limiter._wakeup of asynciolimiter.Limiter(rate=6000.0)>
handle: <Handle Limiter._wakeup>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 61, in uvloop.loop.Handle._run
  File "/root/miniforge3/envs/ccxt/lib/python3.11/site-packages/asynciolimiter.py", line 354, in _wakeup
    assert -leftover_time < self._time_between_calls, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Event loop is too fast. Woke up 1.0000001639127731 ticks early.
```

**Comment by River-Shi** [comment]
> > Using the `asynciolimiter.Limiter` I'm hitting this assertion, unsure what's to be done about it;
> > ```
> > site-packages\asynciolimiter\__init__.py", line 356, in _wakeup
> >     assert -leftover_time < self._time_between_calls, (
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > AssertionError: Event loop is too fast. Woke up 1.9999999979821346 ticks early.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > On Python 3.12, rate limit of ~166.666 with 156 tasks
> 
> same error:
> 
> ```
> Exception in callback <bound method Limiter._wakeup of asynciolimiter.Limiter(rate=6000.0)>
> handle: <Handle Limiter._wakeup>
> Traceback (most recent call last):
>   File "uvloop/cbhandles.pyx", line 61, in uvloop.loop.Handle._run
>   File "/root/miniforge3/envs/ccxt/lib/python3.11/site-packages/asynciolimiter.py", line 354, in _wakeup
>     assert -leftover_time < self._time_between_calls, (
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AssertionError: Event loop is too fast. Woke up 1.0000001639127731 ticks early.
> ```

I am using uvloop and ubuntu 22.4

**Comment by bharel** [comment]
@River-Shi may you try with the normal event loop to make sure it's not a uvloop issue? It would help me debug it well :)
Meanwhile I'll change it to a warning

**Comment by River-Shi** [comment]
> @River-Shi may you try with the normal event loop to make sure it's not a uvloop issue? It would help me debug it well :) Meanwhile I'll change it to a warning

When I changed to normal event loop, it works fine.

**Comment by bharel** [comment]
@River-Shi alright, thank you. I've opened a bug report in cpython. Meanwhile I'll change to a resource warning.

**Comment by River-Shi** [comment]
> @River-Shi alright, thank you. I've opened a bug report in cpython. Meanwhile I'll change to a resource warning.

So it is a cpython bug, not uvloop ?

**Comment by bharel** [comment]
> > @River-Shi alright, thank you. I've opened a bug report in cpython. Meanwhile I'll change to a resource warning.
> 
> So it is a cpython bug, not uvloop ?

It's a specification issue. If CPython will specify the constraint (that asyncio call later can't call earlier than the time specified), uvloop will have to uphold it, but as of now the constraint is not clear.

**Comment by bharel** [comment]
Added clarity on the cpython issue at https://github.com/python/cpython/issues/127859#issuecomment-2538609312

**Comment by River-Shi** [comment]
> Added clarity on the cpython issue at [python/cpython#127859 (comment)](https://github.com/python/cpython/issues/127859#issuecomment-2538609312)

Any new update? I ve switched to a similar project, `aiolimiter `, the problem seems fixed

**Comment by bharel** [comment]
@River-Shi I have changed it to a resource warning for now.

`aiolimiter` doesn't actually fix the problem. The problem is in the Python specification, and perhaps the uvloop implementation. `aiolimiter` is simply less accurate and ignores it.

**Comment by River-Shi** [comment]
> @davidhyman @River-Shi I have changed it to a resource warning for now. You can download the new version 1.1.1 and it'll work fine :-)
> 
> `aiolimiter` doesn't actually fix the problem. The problem is in the Python specification, and perhaps the uvloop implementation. `aiolimiter` is simply less accurate and ignores it.

Tkx

**Comment by davidhyman** [comment]
> I have changed it to a resource warning for now. You can download the new version 1.1.1 and it'll work fine :-)
> 
> `aiolimiter` doesn't actually fix the problem. The problem is in the Python specification, and perhaps the uvloop implementation. `aiolimiter` is simply less accurate and ignores it.

Thank you, I've got around to having another go and it seems to work for me now, though I can't rule out some different implementation as I never committed the original (doh). Sorry I didn't manage to help you with investigation. I've tried it with same rate limit, ~300 concurrent tasks 👍 🤷 🎄
